### ISSUE TITLE
引入lsplant库编译报错了

### ISSUE THREAD

**Issue by anjiuzhe** [LSPosed/LSPlant#85]
你好，由于项目原因，只能使用特定版本的ndk编译。implementation "org.lsposed.lsplant:lsplant-standalone:+后编译提示：

```
Exception in thread "main" java.lang.IllegalArgumentException: Unknown ABI: riscv64
	at com.google.prefab.api.Android$Abi$Companion.fromString(Android.kt:99)
	at com.google.prefab.api.Android$Companion.prebuiltLibraryFromDirectory(Android.kt:399)
	at com.google.prefab.api.Module.<init>(Module.kt:160)
	at com.google.prefab.api.Package.<init>(Package.kt:93)
	at com.google.prefab.cli.Cli$packages$2.invoke(Cli.kt:124)
	at com.google.prefab.cli.Cli$packages$2.invoke(Cli.kt:123)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.google.prefab.cli.Cli.getPackages(Cli.kt:123)
	at com.google.prefab.cli.Cli.validate(Cli.kt:172)
	at com.google.prefab.cli.Cli.run(Cli.kt:189)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:204)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:17)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:396)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:393)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:411)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:436)
	at com.google.prefab.cli.AppKt.main(App.kt:28)
```
配置了具体的支持架构也是一样的，请问要如何排除项目不支持的riscv64架构呢？
```
android { ndk { abiFilters "armeabi-v7a","arm64-v8a"} }
```

**Comment by vvb2060** [comment]
升级AGP
